# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

workspace 'PlugInDemo.xcworkspace'

target 'PlugInDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for running
  pod 'AFNetworking', '4.0.1'
  pod 'Masonry', '1.1.0'
  pod 'SSZipArchive', '2.2.3'
end

target 'GCore' do

project 'GCore/GCore.xcodeproj'

end
